#!/bin/bash
# Generates docs/QUALITY.md from actual code metrics.
# Run: bash scripts/update-quality.sh

set -euo pipefail
cd "$(dirname "$0")/.."

QUALITY_FILE="docs/QUALITY.md"

# Collect metrics
get_lines() { wc -l < "$1" | tr -d ' '; }

get_test_count() {
  local src="$1"
  local test="${src%.ts}.test.ts"
  if [ -f "$test" ]; then
    grep -c '  it(' "$test" 2>/dev/null || echo "0"
  else
    echo "0"
  fi
}

get_grade() {
  local src="$1"
  local lines=$(get_lines "$src")
  local tests=$(get_test_count "$src")
  local test_file="${src%.ts}.test.ts"

  # Types-only files get B automatically
  if echo "$src" | grep -q "types.ts"; then echo "B"; return; fi

  if [ "$tests" -gt 0 ]; then
    if [ "$lines" -lt 100 ]; then echo "A"; else echo "B"; fi
  else
    if [ "$lines" -gt 200 ]; then echo "D"; else echo "C"; fi
  fi
}

# Generate report
cat > "$QUALITY_FILE" << 'HEADER'
# Quality Status

> Auto-generated by `scripts/update-quality.sh`. Do not edit manually.

## Grading: A (tested+clean) / B (partial) / C (no tests, clean) / D (no tests + issues)

HEADER

echo "| File | Lines | Grade | Tests | Has Test File |" >> "$QUALITY_FILE"
echo "|------|-------|-------|-------|---------------|" >> "$QUALITY_FILE"

total_lines=0
total_tests=0
files_with_tests=0
total_files=0

for f in src/lib/*.ts; do
  # Skip test files themselves
  echo "$f" | grep -q '\.test\.ts$' && continue

  lines=$(get_lines "$f")
  tests=$(get_test_count "$f")
  grade=$(get_grade "$f")
  test_file="${f%.ts}.test.ts"
  has_test="No"
  [ -f "$test_file" ] && has_test="Yes"

  basename=$(echo "$f" | sed 's|src/||')
  echo "| \`$basename\` | $lines | **$grade** | $tests | $has_test |" >> "$QUALITY_FILE"

  total_lines=$((total_lines + lines))
  total_tests=$((total_tests + tests))
  [ "$tests" -gt 0 ] && files_with_tests=$((files_with_tests + 1))
  total_files=$((total_files + 1))
done

cat >> "$QUALITY_FILE" << EOF

## Summary
- **Total lib files:** $total_files
- **Files with tests:** $files_with_tests / $total_files
- **Total test cases:** $total_tests
- **Total lib lines:** $total_lines

*Last updated: $(date +%Y-%m-%d)*
EOF

echo "Updated $QUALITY_FILE"
